### ISSUE TITLE
Lauch Issue in version 4.18

### ISSUE THREAD

**Issue by ModHasan** [UE4-OceanProject/OceanProject#55]
I have updated both the dlls, still unable to launch the project.

![error00](https://user-images.githubusercontent.com/33828926/33013030-9c0e0afe-ce08-11e7-82bd-89736332b659.jpg)
![error01](https://user-images.githubusercontent.com/33828926/33013032-9c3db786-ce08-11e7-86fd-6b7d156a6eb6.jpg)

**Comment by vincolus** [comment]
bump

**Comment by TheZoc** [comment]
Apparently this is the same issue as #49. Can you, please, take a look at it and report back? :)

**Comment by TheZoc** [comment]
Hopefully this is fixed on 2422164 😄 
Please, test and report when you can :)

**Comment by ModHasan** [comment]
I have tried both the solutions mentioned in 2422164 and in #49.
Now it is showing only 1 dll to be rebuild, but problem still persists.
I have Visual Studio Community 2017 15.4.4.

![error02](https://user-images.githubusercontent.com/33828926/33113023-339ece20-cf7c-11e7-8c82-4629f3837968.jpg)

**Comment by bitsmear** [comment]
Issue solved for me on 4.18.1 thank you! :)

**Comment by ModHasan** [comment]
It's working fine with 4.18.1. Thanks

**Comment by TheZoc** [comment]
Good to knows! Thanks for the reports! :D

**Comment by P1llus** [comment]
I would like to comment on that this happen again in 4.19, so i will use 4.18 for now. Is this a normal behavior for each release? And if it is, please let me know how to fix it, and i can put up a PR if you want.
